#!/usr/bin/env python3
"""Export and verify the canonical single-sheet KiCad schematic.

No drawing is synthesized here. SVG/PDF come directly from kicad-cli. The README
PNG is only a white-background rasterization of that same native SVG.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
from kicad_native import ROOT, OUT, SCHEMATIC, PCB, run, read_netlist, circuit_from_native, validate_circuit
from check_schematic_labels import check as check_label_clearance


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalized_svg(path):
    # KiCad's SVG title contains the export time, which is not circuit content.
    return re.sub(r'<title>.*?</title>', '<title>Native KiCad schematic</title>',
                  path.read_text(), flags=re.S)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    rasterizer = shutil.which('rsvg-convert')
    if not rasterizer:
        raise SystemExit('Install librsvg (rsvg-convert) to make/check the README PNG.')
    with tempfile.TemporaryDirectory(prefix='.kicad-', dir=ROOT) as directory:
        temp = Path(directory)
        xml = read_netlist(temp)
        components = circuit_from_native(xml)
        validate_circuit(components)
        assert len(xml.findall('./design/sheet')) == 1, 'Expected one native schematic sheet'
        nets = {p['net'] for c in components for p in c['pins'] if p['net']}
        text = SCHEMATIC.read_text()
        labels = re.findall(r'\(global_label\s+"([^"]+)"', text)
        assert len(labels) == len(set(labels)) and set(labels) == nets, 'Net labels must annotate each continuous net once'
        assert not re.search(r'\(sheet\s', text), 'Unexpected hierarchical sheet'
        version = run('version')
        run('sch', 'erc', '--exit-code-violations', '-o', temp/'erc.rpt', SCHEMATIC)
        run('pcb', 'drc', '--schematic-parity', '--exit-code-violations', '-o', temp/'drc.rpt', PCB)
        run('sch', 'export', 'svg', '--black-and-white', '--exclude-drawing-sheet', '-o', temp, SCHEMATIC)
        svg = temp/'power-widget-bench.svg'
        assert 'Image generated by Eeschema-SVG' in svg.read_text()
        checked_labels = check_label_clearance(SCHEMATIC, svg, nets)
        png = temp/'single-sheet.png'
        subprocess.run([rasterizer, '--background-color', 'white', '--width', '2800',
                        '--output', str(png), str(svg)], check=True)
        source_names = ['power-widget-bench.kicad_sch', 'Bench.kicad_sym',
                        'power-widget-bench.kicad_pro', 'power-widget-bench.kicad_pcb']
        sources = {name: digest(OUT/name) for name in source_names}
        report_path = OUT/'single-sheet-check.json'
        if args.check:
            report = json.loads(report_path.read_text())
            assert report['source_sha256'] == sources, 'Source changed: regenerate the native exports'
            assert report['kicad_version'] == version, 'Recheck/export with the recorded KiCad version'
            assert normalized_svg(OUT/'single-sheet.svg') == normalized_svg(svg), 'Stale native SVG'
            assert (OUT/'single-sheet.png').read_bytes() == png.read_bytes(), 'Stale native PNG'
            for name, expected in report['artifact_sha256'].items():
                assert digest(OUT/name) == expected, f'Modified artifact: {name}'
        else:
            pdf = temp/'single-sheet.pdf'
            run('sch', 'export', 'pdf', '--black-and-white', '--exclude-drawing-sheet', '-o', pdf, SCHEMATIC)
            for source, name in [(svg, 'single-sheet.svg'), (pdf, 'single-sheet.pdf'), (png, 'single-sheet.png'),
                                 (temp/'erc.rpt', 'erc.rpt'), (temp/'drc.rpt', 'drc.rpt')]:
                shutil.copyfile(source, OUT/name)
            report = dict(source='power-widget-bench.kicad_sch', kicad_version=version,
                source_sha256=sources, artifact_sha256={name: digest(OUT/name) for name in
                    ['single-sheet.svg', 'single-sheet.pdf', 'single-sheet.png', 'erc.rpt', 'drc.rpt']},
                sheets=1, physical_components=len(components), named_nets=len(nets),
                connected_numbered_pins=sum(p['net'] is not None for c in components for p in c['pins']),
                unconnected_numbered_pins=sum(p['net'] is None for c in components for p in c['pins']),
                each_component_appears_once=True, each_net_label_appears_once=True,
                rendered_net_labels_checked=checked_labels, net_label_wire_overlaps=0,
                all_rendered_text_checked=True, rendered_text_wire_overlaps=0, rendered_text_text_overlaps=0,
                erc_violations=0, drc_violations=0, unconnected_pcb_items=0, schematic_pcb_parity_issues=0,
                svg_and_pdf='Direct kicad-cli exports; no redrawing or graphical postprocessing',
                png='White-background rasterization of the native SVG with librsvg',
                scope='Native CAD checks and export fidelity, not hardware qualification')
            report_path.write_text(json.dumps(report, indent=2)+'\n')
        print(f'{"Checked" if args.check else "Exported"} native KiCad {version}: '
              f'{len(components)} components, {len(nets)} nets, one sheet; ERC/DRC/parity all zero.')


if __name__ == '__main__':
    main()
