#!/usr/bin/env python3
"""Check two-contact topology, not USB-PD or VCONN supply behavior."""
import argparse
from itertools import product
from pathlib import Path

root = Path(__file__).resolve().parents[1]
rows = []
for a, b in product((0, 1), repeat=2):
    endpoint = a ^ b
    assert endpoint != ((1 - a) ^ b)
    rows.append((a, b, a + 1, endpoint + 1, a == b, a != b))
assert sum(r[4] for r in rows) == 2
assert sum(r[5] for r in rows) == 2
assert {r[3] for r in rows} == {1, 2}
lines = ["# CC orientation connectivity", "",
         "Generated by `python tools/orientations.py`. Contact mapping only; no PD, VCONN supply, e-marker, or analog simulation.", "",
         "| Cable flip a | Endpoint / second-cable flip b | Active J_A CC | Captive endpoint CC | Fixed F-F CC path | Crossed F-F CC path |",
         "|---|---|---|---|---|---|"]
for a, b, ja, ep, fixed, crossed in rows:
    lines.append(f"| {a} | {b} | CC{ja} | CC{ep} | {'yes' if fixed else 'NO'} | {'yes' if crossed else 'NO'} |")
lines += ["", "An F-F CC path does not establish cable-identity or VCONN correctness. Each fixed F-F map fails two local orientations. The captive extension keeps both contacts separate in all four cases.", ""]
result = "\n".join(lines)
path = root / "analysis/orientations.md"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if not path.exists() or path.read_text() != result:
        raise SystemExit("Orientation output is stale")
else:
    path.write_text(result)
print("CC connectivity: four captive cases; each fixed F-F mapping fails two cases")
